# Generated by Django 4.2.6 on 2023-11-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('procesador', models.TextField()),
                ('pulgadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moviles_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.TextField()),
                ('color', models.CharField(max_length=15)),
                ('mpx_camara', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Televisores',
            new_name='Televisores_models',
        ),
        migrations.DeleteModel(
            name='Laptops',
        ),
        migrations.DeleteModel(
            name='Moviles',
        ),
    ]
