# Generated by Django 4.2.6 on 2023-11-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_laptops_models_moviles_models_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moviles_models',
            new_name='Moviles',
        ),
    ]
