# Generated by Django 4.2.6 on 2023-11-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_moviles_models_moviles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Televisores_models',
            new_name='Televisores',
        ),
    ]
