# Generated by Django 4.2.6 on 2023-11-09 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_televisores_models_televisores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptops_models',
            new_name='Laptops',
        ),
    ]
