# Generated by Django 4.2.6 on 2023-11-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_rename_laptops_models_laptops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviles',
            name='modelo',
            field=models.CharField(max_length=15),
        ),
    ]
