# Generated by Django 4.2.6 on 2023-12-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_moviles_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviles',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='moviles/'),
        ),
    ]
