# Generated by Django 4.2.6 on 2023-12-16 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_moviles_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviles',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
