# Generated by Django 4.2.6 on 2023-12-09 22:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtrosDatos',
            new_name='DatosExtra',
        ),
    ]
