# Generated by Django 4.2.6 on 2023-12-16 15:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_datosextra_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='biografia',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
